#   ____                 _                            _                                
#  / ___|  _   _   ___  | |_    ___    _ __ ___      / \     _ __    ___    __ _   ___ 
# | |     | | | | / __| | __|  / _ \  | '_ ` _ \    / _ \   | '__|  / _ \  / _` | / __|
# | |___  | |_| | \__ \ | |_  | (_) | | | | | | |  / ___ \  | |    |  __/ | (_| | \__ \
#  \____|  \__,_| |___/  \__|  \___/  |_| |_| |_| /_/   \_\ |_|     \___|  \__,_| |___/
#																			by SoyDavs
messages:
  no_permission: "You do not have permission to use this command."
  region_exists: "A region with the name '{name}' already exists."
  region_message_default: "Welcome to {name}!"
  usage: "Usage: /ca <create|edit|remove|list|gui|pos1|pos2>"
  gui_title: "Custom Areas"
  gui_content: "Please choose an option:"
  gui_buttons:
    - "Create Area"
    - "Edit Area"
    - "Remove Area"
    - "List Areas"
    - "Cancel"
  remove_prompt: "Select an area to remove:"
  confirm_remove_title: "Confirm Removal"
  confirm_remove_content: "Are you sure you want to remove the region '{name}'?"
  edit_prompt: "Select an area to edit:"
  edit_success: "The region '{name}' has been successfully edited."
  create_success: "The region '{name}' has been successfully created."
  edit_area_title: "Edit Area Details"
  edit_area_content: "Editing details for '{name}':"
  edit_area_name_prompt: "New Area Name"
  edit_area_change_pos1_prompt: "Change Position 1"
  edit_area_change_pos2_prompt: "Change Position 2"
  pos1_prompt: "Please set Position 1 using /ca pos1"
  pos2_prompt: "Please set Position 2 using /ca pos2"
  edit_pos1_success: "Position 1 for region '{name}' has been updated."
  edit_pos2_success: "Position 2 for region '{name}' has been updated."
  entering_region_denied: "You do not have permission to enter the region '{name}'."
  list_areas_empty: "There are no regions defined."
  list_areas: "Defined Regions:"


regions: {}
